server:
  port: 8080
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
spring:
  profiles: local
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:h2:file:./kream;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true